# This is blank for now

repository: vm-cb:5000
fqdn_ingress: vip-ashish3.panasonicfa.com
# The git_repo is used for the applicationset
git:
  repo: http://localhost:3000/Basant.Solanky/ha-infr.git
  revision: master

nginx:
  enabled: true

metallb:
  addresses: []
  enabled: true

grafana:
  ingress: 
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2 break;
    path: /grafana(/|$)(.*)
    pathType: Prefix

    hosts:
      - test

prometheus:
  enabled: true
  additionalScrapeConfigs: []
  storageSpec: []
    #spec:
    #  storageClassName: kubegres-openebs-hostpath
    #  accessModes: ["ReadWriteOnce"]
    #  resources:
    #    requests:
    #      storage: 50Gi

  tolerations: []
    # - key: "key"
    #   operator: "Equal"
    #   value: "value"
    #   effect: "NoSchedule"
  resources: []
    #limits:
    #  cpu: 3
    #requests:
    #  cpu: 500m

istio:
  enabled: true

applicationset:
  enabled: true

argocd:
  enabled: true


kubekafka:
  enabled: true

kubegres:
  enabled: true

elk:
  enabled: true

kubernetesDashboard:
  enabled: true
