quay.io:
  images-by-tag-regex:
    prometheus/node-exporter: v1.5.0 #Prometheus
    kiwigrid/k8s-sidecar: 1.22.0 #Prometheus
    prometheus-operator/prometheus-operator: v0.63.0 #Prometheus
    prometheus/alertmanager: v0.25.0 #Prometheus
    prometheus/prometheus: v2.42.0 #Prometheus
    prometheus-operator/prometheus-config-reloader: v0.63.0 #Prometheus

docker.io:
  images-by-tag-regex:
    grafana/grafana: 9.3.8 #Prometheus
    istio/install-cni: 1.15.0$ #Istio
    istio/pilot: 1.15.0$ #Istio

registry.k8s.io:
  images-by-tag-regex:
    ingress-nginx/kube-webhook-certgen: v20221220-controller-v1.5.1-58-g787ea74b6 #Prometheus
    kube-state-metrics/kube-state-metrics: v2.8.2 #Prometheus


k8s.gcr.io:
  image-by-tag-regex:
    ingress-nginx/controller: v1.2.0 #Ingress
