quay.io:
  images-by-tag-regex:
    prometheus/node-exporter: v1.5.0
    kiwigrid/k8s-sidecar: 1.22.0
    prometheus-operator/prometheus-operator: v0.63.0
    prometheus/alertmanager: v0.25.0
    prometheus/prometheus: v2.42.0

docker.io:
  images-by-tag-regex:
    grafana/grafana: 9.3.8

registry.k8s.io:
  images-by-tag-regex:
    ingress-nginx/kube-webhook-certgen: v20221220-controller-v1.5.1-58-g787ea74b6
    kube-state-metrics/kube-state-metrics: v2.8.2
