#quay.io:
#  images-by-tag-regex:
#    prometheus/node-exporter: v1.9.1 #Prometheus
#    kiwigrid/k8s-sidecar: 1.30.0 #Prometheus
#    prometheus-operator/prometheus-operator: v0.82.2 #Prometheus
#    prometheus/alertmanager: v0.28.1 #Prometheus
#    prometheus/prometheus: v3.4.1 #Prometheus
#    prometheus-operator/prometheus-config-reloader: v0.82.2 #Prometheus
#    metallb/controller: v0.14.9 #metallb
#    frrouting/frr: 9.1.0 #metallb
#    metallb/speaker: v0.14.9
#    argoproj/argocd: v2.14.6
#
#docker.io:
#  images-by-tag-regex:
#    grafana/grafana: 12.0.0-security-01 #Prometheus
#    istio/install-cni: 1.17.0$ #Istio
#    istio/pilot: 1.17.0$ #Istio
#    redis: 7.0.15-alpine
#    bats/bats: v1.4.1 #Prometheus


registry.k8s.io:
  images-by-tag-regex:
    kube-apiserver: v1.26.15
    kube-controller-manager: v1.26.15
    kube-scheduler: v1.26.15
    kube-proxy: v1.26.15
    pause: 3.[0-9]+
    etcd: 3.5.10-0
    coredns/coredns: v1.9.3
    kube-state-metrics/kube-state-metrics: v2.15.0 #Prometheus
    ingress-nginx/kube-webhook-certgen: v1.5.3




#k8s.gcr.io:
#  images-by-tag-regex:
#    ingress-nginx/controller: v1.2.0
#
#
#ghcr.io:
#  images-by-tag-regex:
#    flannel-io/flannel: v0.26.7
#    flannel-io/flannel-cni-plugin: v1.6.2-flannel1
#    dexidp/dex: v2.41.1
