quay.io:
  images-by-tag-regex:
    prometheus/node-exporter: v1.5.0 #Prometheus
    kiwigrid/k8s-sidecar: 1.22.0 #Prometheus
    prometheus-operator/prometheus-operator: v0.63.0 #Prometheus
    prometheus/alertmanager: v0.25.0 #Prometheus
    prometheus/prometheus: v2.42.0 #Prometheus
    prometheus-operator/prometheus-config-reloader: v0.63.0 #Prometheus
    metallb/controller: v0.14.9 #metallb
    frrouting/frr: 9.1.0 #metallb
    metallb/speaker: v0.14.9
    argoproj/argocd: v2.14.6

docker.io:
  images-by-tag-regex:
    grafana/grafana: 9.3.8 #Prometheus
    istio/install-cni: 1.17.0$ #Istio
    istio/pilot: 1.17.0$ #Istio
    redis: 7.0.15-alpine


registry.k8s.io:
  images-by-tag-regex:
    ingress-nginx/kube-webhook-certgen: v20221220-controller-v1.5.1-58-g787ea74b6 #Prometheus
    #ingress-nginx/kube-webhook-certgen: v1.1.1 #nginx-ingress
    kube-state-metrics/kube-state-metrics: v2.8.2 #Prometheus
    kube-apiserver: v1.26.15
    kube-controller-manager: v1.26.15
    kube-scheduler: v1.26.15
    kube-proxy: v1.26.15
    pause: 3.[0-9]+
    etcd: 3.5.10-0
    coredns/coredns: v1.9.3


k8s.gcr.io:
  images-by-tag-regex:
    ingress-nginx/controller: v1.2.0


ghcr.io:
  images-by-tag-regex:
    flannel-io/flannel: v0.26.7
    flannel-io/flannel-cni-plugin: v1.6.2-flannel1
    dexidp/dex: v2.41.1
