apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sm-main-kafka
  namespace: sm-kafka
spec:
  kafka:
    version: 2.8.0
    replicas: {{ .Values.kafka.replicas }}
    image: {{ .Values.kafka.image.imageRegistry }} /quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32100
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "2.8"
      max.message.bytes: 10000000
      replica.fetch.max.bytes: 10000000
      socket.request.max.bytes: 500000000
      log.retention.bytes: 107374182400
      log.retention.hours: 168
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.pv.storage }}Gi
        class: kafka-local-storage
        deleteClaim: false
    resources:
      requests:
        cpu: {{ .Values.kafka.resources.requests.cpu }}
        memory: {{ .Values.kafka.resources.requests.memory }}
    template:
      pod:
        tolerations:
          - key: "pod"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
          - key: "pod"
            operator: "Equal"
            value: "kafka"
            effect: "NoExecute"
        affinity:
          nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: kafkanode
                      operator: In
                      values:
                      - kafka
  zookeeper:
    image: {{ .Values.kafka.image.imageRegistry }} /quay.io/strimzi/kafka:0.24.0-kafka-2.8.0
    replicas: {{ .Values.kafka.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.pv.storage }}Gi
      class: kafka-local-storage
      deleteClaim: false
    resources:
      requests:
        cpu: {{ .Values.kafka.resources.requests.cpu }}
        memory: {{ .Values.kafka.resources.requests.memory }}
    template:
      pod:
        tolerations:
          - key: "pod"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
          - key: "pod"
            operator: "Equal"
            value: "kafka"
            effect: "NoExecute"
        affinity:
          nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: kafkanode
                      operator: In
                      values:
                      - kafka
  entityOperator:
    topicOperator: {}
    userOperator: {}
