kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-elk
reclaimPolicy: Retain
allowVolumeExpansion: true
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer