kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kibana-ingress
  namespace: sm-elasticsearch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite: "^/kibana(/|$)(.*)$ /$1 break;"
spec:
  rules:
    - host: {{ .Values.K8S_VHOSTNAME }} 
      http:
        paths:
          - path: /kibana(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sm-main-kibana-kb-http
                port:
                  number: 5601
