{{- if .Values.argocd.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.9.0
    chart: argo-cd
    helm:
      releaseName: argocd
      values: |
        global:
          domain: {{ .Values.fqdn_ingress }}
        configs:
          params:
            "server.rootpath": "/argo-cd"
            "server.basehref": "/argo-cd"
        server:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
          
            path: /argo-cd(/|$)(.*)
            pathType: Prefix
          
          
