{{- if .Values.elk.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk
  namespace: argocd
spec:
  destination:
    namespace: sm-elasticsearch
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.git.repo }}
    path: charts/dashboard
    targetRevision: {{ .Values.git.revision }}
{{- end -}}

