{{- if .Values.istio.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  source:
    repoURL: {{ .Values.git.repo }}
    path: charts/vendor/istio/base
    targetRevision: {{ .Values.git.revision }}
    helm:
      releaseName: istio-base
      values: |
        global:
          imageRegistry: {{ .Values.repository }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.git.repo }}
    path: charts/vendor/istio/cni
    targetRevision: {{ .Values.git.revision }}
    helm:
      releaseName: istio-cni
      values: |
        global:
          hub: {{ .Values.repository }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: {{ .Values.git.repo }}
    path: charts/vendor/istio/istiod
    targetRevision: {{ .Values.git.revision }}
    helm:
      releaseName: istiod
      values: |
        pilot:	
          image: {{ .Values.repository}}/pilot:1.17.0
        global:
          hub: {{ .Values.repository }}/istio
        meshConfig:
          rootNamespace: "istio-system"
          extensionProviders:
            - name: "gateway-authorizer-http"
              envoyExtAuthzHttp:
                service: "panasonic-user-authorization-coreapp-gateway-service.smpum.svc.cluster.local"
                port: "8000"
                includeRequestHeadersInCheck: ["authorization", "tenantId"]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: {{ .Values.git.repo }}
    path: charts/vendor/istio/gateway
    targetRevision: {{ .Values.git.revision }}
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: ClusterIP
        global:
           hub: {{ .Values.repository }}
{{- end -}}
