{{- if .Values.istio.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.15.0
    chart: base
    helm:
      releaseName: istio-base
      values: |
        global:
          imageRegistry: {{ .Values.repository }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.15.0
    chart: cni
    helm:
      releaseName: istio-cni
      values: |
        cni:
          hub: {{ .Values.repository }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.15.0
    chart: istiod
    helm:
      releaseName: istiod
      values: |
        pilot:
          hub: {{ .Values.repository }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.15.0
    chart: gateway
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: ClusterIP
        pilot:
           hub: {{ .Values.repository }}
        meshConfig:
          extensionProviders:
            - name: "gateway-authorizer-http"
              envoyExtAuthzHttp:
                service: "panasonic-user-authorization-coreapp-gateway-service.smpum.svc.cluster.local"
                port: "8000"
                includeRequestHeadersInCheck: ["authorization", "tenantId"]
{{- end -}}
