{{- if .Values.metallb.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helper
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.gitRepo }}
    path: charts/metallb-helper
    targetRevision: metallb
    helm:
      releaseName: metallb-helper
      values: |
        addresses: 
          {{- range .Values.metallb.addresses }}
          - {{ toYaml . }}
          {{- end }}
{{- end -}}
