{{- if .Values.metallb.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.git.repo }}
    path: charts/vendor/metallb
    targetRevision: {{ .Values.git.revision }}
    helm:
      releaseName: metallb
      values: |
        controller:
          image:
            repository: {{ .Values.repository }}/controller
        speaker:
          image:
            repository: {{ .Values.repository }}/speaker
          frr:
            image:
              repository: {{ .Values.repository }}/frr
{{- end -}}
