{{- if .Values.nginx.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.2
    chart: ingress-nginx
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          config:
            proxy-buffer-size: 16k
          service:
            externalTrafficPolicy: Local
          image:
            digest: ""
            registry: {{ .Values.repository }}
            image: controller
          admissionWebhooks:
            patch:
              image:
                registry: {{ .Values.repository }}
                image: kube-webhook-certgen
                digest: ""
{{- end -}}
